Reaper operator updates for operator sdk 1.6.1
k8ssandra/k8ssandra pull request #1160
Opened 2021-11-03 02:34 UTC by Miles-Garnsey

**What this PR does**:

* Upgrade reaper-operator manifests to align with latest config/ in main repo. (operator-sdk 1.6.1/controller-runtime 0.9.2).
* Brings CRD API versions up to v1 from v1beta1, making compatible with k8s 1.22.
* Add additional RBAC configs required by leader election in more recent operator-sdk versions.

**Which issue(s) this PR fixes**:

#1150.

**Checklist**
- [ ] Changes manually tested
- [ NA ] Automated Tests added/updated
- [ NA ] Documentation added/updated
- [ Y ] CHANGELOG.md updated (not required for documentation PRs)
- [ NA ] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

2021-11-04 00:16 UTC, Miles-Garnsey commented
Just realised I should update the reaper-operator image on this. Not sure if it has been built yet. Marking as draft.

2021-11-04 02:00 UTC, Miles-Garnsey commented
Bumped reaper-operator version to latest to pick up current set of changes. All tests still pass - ready for review.

2021-11-04 07:48 UTC, adejanovski commented
I'll pick that review up

2021-11-04 14:46 UTC, adejanovski requested changes
We first need to get a reaper-operator release out before we can move forward with this PR, and we'll need to update the subchart numbers accordingly.

2021-11-04 20:54 UTC, Miles-Garnsey commented on charts/reaper-operator/values.yaml
> +  tag: latest
That makes sense to me. I'll raise a ticket to do snapshot releases of Reaper when PRs are merged.

2021-11-12 04:56 UTC, Miles-Garnsey commented
Requested changes have been made now that the reaper-operator v0.3.5 version is out. Ready for merge. @adejanovski can you please approve?

2021-11-15 08:38 UTC, adejanovski approved these changes

2021-11-15 10:22 UTC, merged