K8SSAND-973: Add support for service account annotations in helm chart
k8ssandra/k8ssandra pull request #1410
Opened 2022-05-13 16:19 UTC by perplexa

**What this PR does**:

Add support for service account annotations in helm chart

**Which issue(s) this PR fixes**:
Fixes #1135 

**Checklist**
- [x] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

2022-06-08 19:46 UTC, jsanda requested changes

2022-06-08 19:46 UTC, jsanda commented on charts/k8ssandra-common/Chart.yaml
> +version: 0.28.5
This is already 0.28.5 in main. Can you bump this to 0.28.6.

2022-06-08 19:46 UTC, jsanda commented on charts/k8ssandra/Chart.yaml
> +    version: 0.28.5
All the other charts depend on k8ssandra-common as well. You will need to update the dependencies in other charts and then bump their chart versions.

2022-06-08 19:47 UTC, jsanda commented
You need to rebase off main to fix the lint error.

2022-06-10 08:59 UTC, perplexa commented
@jsanda done ✅

2022-06-14 16:40 UTC, perplexa commented
@jsanda all done! 👍🏼

2022-06-15 19:36 UTC, merged