Allow to run subset of unit tests
k8ssandra/k8ssandra pull request #398
Opened 2021-02-22 07:07 UTC by burmanm

**What this PR does**:
Adds TESTS parameter to the Makefile, allowing the following behavior:

```
⋊> ~/p/g/d/k8ssandra on main ⨯ make TESTS=".*auth.*" unit-test                                                                                                                                                                                                                           09:01:49
go test -v -test.timeout=3m ./tests/unit/... -coverprofile cover.out -args -ginkgo.focus=".*auth.*"
=== RUN   TestTemplateUnitTests
Running Suite: Unit tests suite
===============================
Random Seed: 1613977317
Will run 7 of 126 specs
```

With just ``make unit-test`` all unit tests (template tests basically) are run and ``make test`` behavior will remain the same as before. ``make pkg-test`` allows running the pkg/* tests only.

**Which issue(s) this PR fixes**:

**Checklist**
- [x] Changes manually tested
- [ ] Chart versions updated (if necessary)
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

2021-02-22 21:04 UTC, jsanda requested changes
@burmanm Thanks for this! 

I have one, small additional request. Can you make the `-v` option configurable and have it off by default?

2021-02-23 12:40 UTC, jdonenine reviewed
Minor question about the arg name, otherwise this is a nice add.

2021-02-23 13:07 UTC, burmanm commented on Makefile
> +TESTS=all
There's no reason to restrict it for unit tests only in the future. We simply don't have other tests yet that would benefit from filtering.

2021-02-23 13:16 UTC, burmanm commented
@jsanda Here you go:

```
⋊> ~/p/g/d/k8ssandra on conditional_tests ⨯ make test
go fmt ./pkg/...
go fmt ./tests/...
go vet ./pkg/...
go vet ./tests/...
go test  -test.timeout=3m ./tests/unit/... -coverprofile cover.out
ok      github.com/k8ssandra/k8ssandra/tests/unit       32.589s coverage: [no statements]
?       github.com/k8ssandra/k8ssandra/tests/unit/utils/cassdc  [no test files]
?       github.com/k8ssandra/k8ssandra/tests/unit/utils/helm    [no test files]
?       github.com/k8ssandra/k8ssandra/tests/unit/utils/kubeapi [no test files]
?       github.com/k8ssandra/k8ssandra/tests/unit/utils/traefik [no test files]
mkdir -p /home/michael/projects/git/datastax/k8ssandra/testbin
test -f /home/michael/projects/git/datastax/k8ssandra/testbin/setup-envtest.sh || curl -sSLo /home/michael/projects/git/datastax/k8ssandra/testbin/setup-envtest.sh https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/master/hack/setup-envtest.sh
source /home/michael/projects/git/datastax/k8ssandra/testbin/setup-envtest.sh && fetch_envtest_tools /home/michael/projects/git/datastax/k8ssandra/testbin && setup_envtest_env /home/michael/projects/git/datastax/k8ssandra/testbin && go test  -test.timeout=3m ./pkg/... -coverprofile cover.out
Using cached envtest tools from /home/michael/projects/git/datastax/k8ssandra/testbin
setting up env vars
ok      github.com/k8ssandra/k8ssandra/pkg/cleaner      7.935s  coverage: 50.0% of statements
⋊> ~/p/g/d/k8ssandra on conditional_tests ⨯
```

2021-02-23 14:34 UTC, jsanda approved these changes

2021-02-23 14:34 UTC, merged