Update architecture docs - monitoring
k8ssandra/k8ssandra pull request #527
Opened 2021-03-09 22:14 UTC by jeffreyscarpenter

Proposed updates to monitoring architecture page.

2021-03-10 15:09 UTC, johnwfrancis requested changes

2021-03-10 15:09 UTC, johnwfrancis commented on docs/content/en/docs/architecture/monitoring/_index.md
> +With K8ssandra and cass-operator,  This exposes Cassandra node-level metrics in the Prometheus format, covering everything from operations per second and latency, to compaction throughput and heap us
Looks like a fragment...

2021-03-10 21:36 UTC, jeffreyscarpenter commented on docs/content/en/docs/architecture/monitoring/_index.md
> +With K8ssandra and cass-operator,  This exposes Cassandra node-level metrics in the Prometheus format, covering everything from operations per second and latency, to compaction throughput and heap us
updated to remove fragment

2021-03-10 21:43 UTC, johnwfrancis approved these changes

2021-03-12 16:24 UTC, bradfordcp approved these changes

2021-03-12 16:36 UTC, bradfordcp requested changes

2021-03-12 16:36 UTC, bradfordcp commented on docs/content/en/docs/architecture/monitoring/_index.md
> +* The Cassandra nodes in a K8ssandra-managed cluster are organized in one or more data centers, each of which is represented as a Kubernetes [StatefulSet](https://kubernetes.io/docs/concepts/workload
Each _rack_ is a stateful set. A 3 rack DC will be comprised of 3 stateful sets. Also, "data center" is considered a single word "datacenter".

2021-03-12 16:36 UTC, bradfordcp commented on docs/content/en/docs/architecture/monitoring/_index.md
> +* The Cassandra nodes in a K8ssandra-managed cluster are organized in one or more data centers, each of which is represented as a Kubernetes [StatefulSet](https://kubernetes.io/docs/concepts/workload
```suggestion
* The Cassandra nodes in a K8ssandra-managed cluster are organized in one or more datacenters, each of which is composed of one or more racks. Each rack represents a failure domain with replicas being placed across multiple racks (if present). In Kubernetes, racks are represented as [StatefulSets](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/). (We'll focus here on details of the Cassandra node related to monitoring, you can see other details about Cassandra nodes such as how storage is managed on the [Cassandra architecture](/docs/architecture/cassandra) page.)
```

2021-03-12 16:36 UTC, bradfordcp commented on docs/content/en/docs/architecture/monitoring/_index.md
> +* An instance of the Prometheus Operator is deployed using a Replica Set. The `kube-prometheus-stack` also defines several useful Kubernetes [custom resources (CRDs)](https://kubernetes.io/docs/conce
We provide a service monitor for Stargate when it is enabled. I don't know if you want to update this text based on that information.

2021-03-12 16:36 UTC, bradfordcp commented on docs/content/en/docs/architecture/monitoring/_index.md
> +* An instance of the Prometheus Operator is deployed using a Replica Set. The `kube-prometheus-stack` also defines several useful Kubernetes [custom resources (CRDs)](https://kubernetes.io/docs/conce
```suggestion
* An instance of the Prometheus Operator is deployed using a Replica Set. The `kube-prometheus-stack` also defines several useful Kubernetes [custom resources (CRDs)](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) that the Prometheus Operator uses to manage Prometheus. One of these is the `ServiceMonitor`. K8ssandra uses `ServiceMonitor` resources, specifying labels selectors to indicate the Cassandra pods to connect to in each datacenter, and how to relabel each metric as it is stored in Prometheus. K8ssandra provides a `ServiceMonitor` for Stargate when it is enabled. Users may also configure `ServiceMonitors` to pull metrics from the various operators, but pre-configured instances are not provided at this time.
```

2021-03-12 16:36 UTC, bradfordcp commented on docs/content/en/docs/architecture/monitoring/_index.md
> +* The `AlertManager` is an additional resource provided by `kube-prometheus-stack` that can be configured to specify thresholds for specific metrics that will trigger alerts. Use of this feature is a
Users may enable, and configure, AlertManager through the `values.yaml` file. Maybe we should direct them to check the options out at https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml#L114-L595?

2021-03-12 16:57 UTC, bradfordcp commented
Should the lower half of this page be bulleted? Is there a reason we're not using paragraphs?

2021-03-12 20:13 UTC, bradfordcp approved these changes

2021-03-12 20:14 UTC, merged