remove jolokia integration
k8ssandra/k8ssandra pull request #597
Opened 2021-03-28 22:59 UTC by jsanda

**What this PR does**:
Removes the Jolokia integration. Jolokia is no longer needed since Medusa now supports management-api for creating snapshots. This PR allows us to get rid of the `get-jolokia` init container as well as remove the jolokia agent from Cassandra.

The Changes in Medusa are in master but not yet released. This PR updates the default Medusa image to one build from the master branch in Medusa. As soon we have a new release of Medusa we can update the default image again. That shouldn't hold up this PR though.

**Which issue(s) this PR fixes**:
Fixes #533

**Checklist**
- [x] Changes manually tested
- [x] Chart versions updated (if necessary)
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

2021-03-29 05:53 UTC, burmanm commented on charts/k8ssandra/templates/cassandra/cassdc.yaml
> -          - name: JVM_EXTRA_OPTS
When removing this line, the above "Env" part must be fixed also (it's no longer enough to have either medusa or reaper enabled to render the env)

2021-03-29 14:43 UTC, emerkle826 requested changes
This looks good, except for the template issue @burmanm pointed out.

2021-03-30 12:39 UTC, burmanm commented on charts/k8ssandra/templates/cassandra/cassdc.yaml
> +{{/*      {{- end }}*/}}
Same as above.

2021-03-30 13:55 UTC, burmanm commented on charts/k8ssandra/Chart.yaml
> +version: 1.0.5-4
Missed this still, the github PR review shows the old version, but this is now 1.1.0-SNAPSHOT in the master, so updating this to 1.0.5-4 doesn't work.

2021-04-07 13:39 UTC, emerkle826 approved these changes

2021-04-07 13:43 UTC, burmanm commented
Should be fine after rebase.

2021-04-07 17:01 UTC, merged