Implement unit tests for templates of CassandraDatacenter and Reaper
k8ssandra/k8ssandra pull request #99
Opened 2020-11-28 14:38 UTC by burmanm

2020-12-04 20:47 UTC, jsanda requested changes
Did initial review on the first couple Reaper tests. I will add follow up reviews for the Medusa and other tests. 

This is looking awesome :) Thanks!

2020-12-04 21:10 UTC, burmanm commented on tests/template_cassdc_test.go
> +			options := &helm.Options{
These are both technically tested in the next section when reaper is disabled again (as only the medusa ones are allowed to be found).

2020-12-04 21:21 UTC, jsanda commented on tests/template_cassdc_test.go
> +			}
When medusa is enabled we also add volume and volume mounts. We want to verify those as well.

2020-12-04 21:25 UTC, jsanda requested changes

2020-12-04 21:25 UTC, jsanda commented on tests/template_cassdc_test.go
> +		It("enabling only medusa", func() {
When medusa is enabled we also add volume and volume mounts. We want to verify those as well.

2020-12-04 21:25 UTC, jsanda commented on tests/template_cassdc_test.go
> +			options := &helm.Options{
Good point. I hadn't considered that. One thing though that is missing in the medusa test is a check to verify that `LOCAL_JMX` is not set.

2020-12-04 21:25 UTC, jsanda commented on tests/template_reaper_test.go
> +			// Requires new version of reaper-operator and k8ssandra PR merged
Those changes have been merged.

2020-12-07 18:07 UTC, burmanm commented on tests/template_cassdc_test.go
> +			options := &helm.Options{
Technically is:

```
Expect(len(cassdc.Spec.PodTemplateSpec.Spec.Containers[0].Env)).To(Equal(1))			Expect(cassdc.Spec.PodTemplateSpec.Spec.Containers[0].Env[0].Name).To(Equal("JVM_EXTRA_OPTS"))
``

There can be only one Env-variable and it has to be JVM_EXTRA_OPTS, so no LOCAL_JMX is possible. But I'll add one more check to the disable reaper that there's no env variables at all.

2020-12-07 18:26 UTC, burmanm commented
I could not add uncomment the Autoscheduler part as each time I run `go test -v ./...` it will simply modify my go.mod to this:

``github.com/k8ssandra/reaper-operator v0.0.0-20201204054951-d4834fcfac4d``

No replace, no edit.. nothing helps.

2020-12-08 04:45 UTC, jsanda requested changes
I made a couple small changes in `template_reaper_test.go` to get it passing. The reaper-operator dependency in go.mod was not changed.

```
Ran 7 of 7 Specs in 0.644 seconds
SUCCESS! -- 7 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestTests (0.65s)
PASS
ok  	github.com/k8ssandra/k8ssandra/tests	0.683s
```

 I also added a Makefile. I pushed my two commits to my [fork](https://github.com/jsanda/k8ssandra/tree/template_unit_tests). 

Can you incorporate these changes?

2020-12-08 04:45 UTC, jsanda commented on tests/template_reaper_test.go
> +			//Expect(reaper.Spec.ServerConfig.Autoscheduler).ToNot(BeNil())
I uncommented and changed the property name to `reaper.Spec.ServerConfig.AutoScheduling`.

2020-12-08 04:45 UTC, jsanda commented on tests/template_reaper_test.go
> +				SetStrValues:   map[string]string{"autoscheduling": "true"},
The property name here should be `repair.reaper.autoschedule`.

2020-12-08 17:39 UTC, jeffbanks approved these changes
Overall LGTM.

One comment, there may be some collaboration and sharing of the [`test util module`](https://github.com/k8ssandra/k8ssandra/blob/f90a29de0d19eab0838663a223e54ab6769b240e/tests/integration/util/lib.go) functions applicable to unit test `setup` (i.e. setup and management of options).  

We could construct a similar module for `unit tests` w/ our standardized set of Terratest, Ginkgo, and Omega APIs.

2020-12-08 21:03 UTC, jsanda approved these changes

2020-12-08 21:04 UTC, merged